# Generated by Django 2.0.1 on 2018-01-29 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciaEstudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_experiencia', models.CharField(choices=[('Principiante', 'Principiante'), ('Intermedio', 'Intermedio'), ('Experimentado', 'Experimentado')], default='Principiante', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('video', models.TextField(blank=True, null=True)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('free_preview', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Platos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SerieTutotiales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivado', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('experianciaEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoriales.ExperienciaEstudiante')),
                ('platos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoriales.Platos')),
            ],
        ),
        migrations.AddField(
            model_name='leccion',
            name='serie_tutoriales',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutoriales.SerieTutotiales'),
        ),
    ]
