# Generated by Django 2.0.1 on 2018-01-29 21:06

from django.db import migrations


class Migration(migrations.Migration):
    atomic=False
    dependencies = [
        ('tutoriales', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SerieTutotiales',
            new_name='SerieTutoriales',
        ),
    ]
