# Generated by Django 2.0.1 on 2018-01-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriales', '0002_auto_20180129_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='length',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
