# Generated by Django 2.0.1 on 2018-01-30 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoriales', '0004_auto_20180130_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serietutoriales',
            old_name='experiancia_estudiante',
            new_name='experiencia_estudiante',
        ),
    ]
